name: studytrack_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5   

  dio: ^5.4.3
  shared_preferences: ^2.2.3

  get_it: ^7.7.0
  
  dartz: ^0.10.1

  studytrack_design_system:
    git:
      url: https://github.com/FerSV4/studytrack-design-system.git
      ref: main
  image_picker: ^1.2.2
  permission_handler: ^12.0.3
  app_links: ^7.0.0
  widgetbook: ^3.23.0
  local_auth: ^3.0.1
  jwt_decoder: ^2.0.1
  connectivity_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
